### ISSUE TITLE
Watson: Integrate into Backend Process Worker

### ISSUE THREAD

**Issue by MerrybyPractice** [marv-the-paranoid-android/ATATvI#4]

**Comment by marvincolgin** [comment]
Pricing Watson...

100k queries is like $880. I submitted a query for student pricing. But I think this means we need to weed down the dataset, pretty drastically. Maybe this means we still load all the data, but the worker will be selective.

```
1 - 250,000 | $0.0088 USD/api call
250,001 - 5,000,000 | $0.0013 USD/api call
5,000,000+ | $0.0008 USD/api call
```
